### ISSUE TITLE
Links to repos doesn´t work

### ISSUE THREAD

**Issue by Jantaroshi** [best-lucky1030/NFT-Projects-Overview#4]
Hi Lucky,

Links to github repos unforunately doesn´t work... :(
I wanted to see stakings and some other repos, but 404

Have a nice day

**Comment by best-lucky1030** [comment]
@catoshicatamoto 
Those repos are under private repos. You are going to build the staking mechanism or just seeing the codebase?
You can contact me via discord.
Venture#1981
This is my discord username.

**Comment by catoshicatamoto** [comment]
Hey thanks for answer
I am trying to learn from best and projects you have done looks amazing
So I would learn from it and probably use it
And btw coinflip doesnt work too (even on vercel it has some error)

I will add you on discord 
Thank you
Have awesome day

**Comment by best-lucky1030** [comment]
@catoshicatamoto 
did you follow to readme for coinflip? Ok. let's move to discord.
